// Code generated by mockery v2.53.5. DO NOT EDIT.

package auth

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
	ports "todoapp/services/user-service/internal/ports"
)

// MockTokenManager is an autogenerated mock type for the TokenManager type
type MockTokenManager struct {
	mock.Mock
}

// GenerateAccessToken provides a mock function with given fields: payload
func (_m *MockTokenManager) GenerateAccessToken(payload ports.TokenPayload) (string, time.Time, error) {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(ports.TokenPayload) (string, time.Time, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func(ports.TokenPayload) string); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(ports.TokenPayload) time.Time); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(ports.TokenPayload) error); ok {
		r2 = rf(payload)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GenerateRefreshToken provides a mock function with given fields: payload, tokenID
func (_m *MockTokenManager) GenerateRefreshToken(payload ports.TokenPayload, tokenID string) (string, time.Time, error) {
	ret := _m.Called(payload, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(ports.TokenPayload, string) (string, time.Time, error)); ok {
		return rf(payload, tokenID)
	}
	if rf, ok := ret.Get(0).(func(ports.TokenPayload, string) string); ok {
		r0 = rf(payload, tokenID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(ports.TokenPayload, string) time.Time); ok {
		r1 = rf(payload, tokenID)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(ports.TokenPayload, string) error); ok {
		r2 = rf(payload, tokenID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ParseAccessToken provides a mock function with given fields: token
func (_m *MockTokenManager) ParseAccessToken(token string) (*ports.TokenClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccessToken")
	}

	var r0 *ports.TokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*ports.TokenClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *ports.TokenClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.TokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseRefreshToken provides a mock function with given fields: token
func (_m *MockTokenManager) ParseRefreshToken(token string) (*ports.TokenClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefreshToken")
	}

	var r0 *ports.TokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*ports.TokenClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *ports.TokenClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.TokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTokenManager creates a new instance of MockTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenManager {
	mock := &MockTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
