// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: proto/analytics/v1/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskEventType int32

const (
	TaskEventType_TASK_EVENT_TYPE_UNSPECIFIED TaskEventType = 0
	TaskEventType_TASK_EVENT_TYPE_CREATED     TaskEventType = 1
	TaskEventType_TASK_EVENT_TYPE_COMPLETED   TaskEventType = 2
	TaskEventType_TASK_EVENT_TYPE_DELETED     TaskEventType = 3
)

// Enum value maps for TaskEventType.
var (
	TaskEventType_name = map[int32]string{
		0: "TASK_EVENT_TYPE_UNSPECIFIED",
		1: "TASK_EVENT_TYPE_CREATED",
		2: "TASK_EVENT_TYPE_COMPLETED",
		3: "TASK_EVENT_TYPE_DELETED",
	}
	TaskEventType_value = map[string]int32{
		"TASK_EVENT_TYPE_UNSPECIFIED": 0,
		"TASK_EVENT_TYPE_CREATED":     1,
		"TASK_EVENT_TYPE_COMPLETED":   2,
		"TASK_EVENT_TYPE_DELETED":     3,
	}
)

func (x TaskEventType) Enum() *TaskEventType {
	p := new(TaskEventType)
	*p = x
	return p
}

func (x TaskEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_analytics_v1_analytics_proto_enumTypes[0].Descriptor()
}

func (TaskEventType) Type() protoreflect.EnumType {
	return &file_proto_analytics_v1_analytics_proto_enumTypes[0]
}

func (x TaskEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEventType.Descriptor instead.
func (TaskEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

type TrackTaskEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       TaskEventType `protobuf:"varint,1,opt,name=type,proto3,enum=analytics.v1.TaskEventType" json:"type,omitempty"`
	UserId     int64         `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId     int64         `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status     string        `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Priority   string        `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	OccurredAt int64         `protobuf:"varint,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
}

func (x *TrackTaskEventRequest) Reset() {
	*x = TrackTaskEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_v1_analytics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackTaskEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackTaskEventRequest) ProtoMessage() {}

func (x *TrackTaskEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackTaskEventRequest.ProtoReflect.Descriptor instead.
func (*TrackTaskEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *TrackTaskEventRequest) GetType() TaskEventType {
	if x != nil {
		return x.Type
	}
	return TaskEventType_TASK_EVENT_TYPE_UNSPECIFIED
}

func (x *TrackTaskEventRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TrackTaskEventRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TrackTaskEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TrackTaskEventRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *TrackTaskEventRequest) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

type TrackTaskEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackTaskEventResponse) Reset() {
	*x = TrackTaskEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_v1_analytics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackTaskEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackTaskEventResponse) ProtoMessage() {}

func (x *TrackTaskEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackTaskEventResponse.ProtoReflect.Descriptor instead.
func (*TrackTaskEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

type DailyTaskMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date           string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	CreatedTasks   int32  `protobuf:"varint,3,opt,name=created_tasks,json=createdTasks,proto3" json:"created_tasks,omitempty"`
	CompletedTasks int32  `protobuf:"varint,4,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	TotalTasks     int32  `protobuf:"varint,5,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
}

func (x *DailyTaskMetrics) Reset() {
	*x = DailyTaskMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_v1_analytics_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyTaskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyTaskMetrics) ProtoMessage() {}

func (x *DailyTaskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyTaskMetrics.ProtoReflect.Descriptor instead.
func (*DailyTaskMetrics) Descriptor() ([]byte, []int) {
	return file_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *DailyTaskMetrics) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DailyTaskMetrics) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyTaskMetrics) GetCreatedTasks() int32 {
	if x != nil {
		return x.CreatedTasks
	}
	return 0
}

func (x *DailyTaskMetrics) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *DailyTaskMetrics) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

type GetDailyMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date   string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *GetDailyMetricsRequest) Reset() {
	*x = GetDailyMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_v1_analytics_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDailyMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyMetricsRequest) ProtoMessage() {}

func (x *GetDailyMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetDailyMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetDailyMetricsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetDailyMetricsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetDailyMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics *DailyTaskMetrics `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *GetDailyMetricsResponse) Reset() {
	*x = GetDailyMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_v1_analytics_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDailyMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyMetricsResponse) ProtoMessage() {}

func (x *GetDailyMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetDailyMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetDailyMetricsResponse) GetMetrics() *DailyTaskMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_proto_analytics_v1_analytics_proto protoreflect.FileDescriptor

var file_proto_analytics_v1_analytics_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63,
	0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e,
	0x76, 0x31, 0x22, 0xcf, 0x01, 0x0a, 0x15, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x6e, 0x61,
	0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x54, 0x61, 0x73,
	0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xae,
	0x01, 0x0a, 0x10, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x22,
	0x45, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x53, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69,
	0x6c, 0x79, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2a, 0x89, 0x01, 0x0a, 0x0d,
	0x54, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a,
	0x1b, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b,
	0x0a, 0x17, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x54,
	0x41, 0x53, 0x4b, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43,
	0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x54, 0x41,
	0x53, 0x4b, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x32, 0xcf, 0x01, 0x0a, 0x10, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x74, 0x69, 0x63, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x0e,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x23,
	0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x44, 0x61, 0x69, 0x6c, 0x79, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x24, 0x2e, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x61, 0x69, 0x6c, 0x79, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x74, 0x6f, 0x64,
	0x6f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x6e, 0x61, 0x6c,
	0x79, 0x74, 0x69, 0x63, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_v1_analytics_proto_rawDescData = file_proto_analytics_v1_analytics_proto_rawDesc
)

func file_proto_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_analytics_v1_analytics_proto_rawDescData)
	})
	return file_proto_analytics_v1_analytics_proto_rawDescData
}

var file_proto_analytics_v1_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_analytics_v1_analytics_proto_goTypes = []any{
	(TaskEventType)(0),              // 0: analytics.v1.TaskEventType
	(*TrackTaskEventRequest)(nil),   // 1: analytics.v1.TrackTaskEventRequest
	(*TrackTaskEventResponse)(nil),  // 2: analytics.v1.TrackTaskEventResponse
	(*DailyTaskMetrics)(nil),        // 3: analytics.v1.DailyTaskMetrics
	(*GetDailyMetricsRequest)(nil),  // 4: analytics.v1.GetDailyMetricsRequest
	(*GetDailyMetricsResponse)(nil), // 5: analytics.v1.GetDailyMetricsResponse
}
var file_proto_analytics_v1_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.v1.TrackTaskEventRequest.type:type_name -> analytics.v1.TaskEventType
	3, // 1: analytics.v1.GetDailyMetricsResponse.metrics:type_name -> analytics.v1.DailyTaskMetrics
	1, // 2: analytics.v1.AnalyticsService.TrackTaskEvent:input_type -> analytics.v1.TrackTaskEventRequest
	4, // 3: analytics.v1.AnalyticsService.GetDailyMetrics:input_type -> analytics.v1.GetDailyMetricsRequest
	2, // 4: analytics.v1.AnalyticsService.TrackTaskEvent:output_type -> analytics.v1.TrackTaskEventResponse
	5, // 5: analytics.v1.AnalyticsService.GetDailyMetrics:output_type -> analytics.v1.GetDailyMetricsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_analytics_v1_analytics_proto_init() }
func file_proto_analytics_v1_analytics_proto_init() {
	if File_proto_analytics_v1_analytics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_analytics_v1_analytics_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TrackTaskEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_analytics_v1_analytics_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TrackTaskEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_analytics_v1_analytics_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DailyTaskMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_analytics_v1_analytics_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetDailyMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_analytics_v1_analytics_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetDailyMetricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_analytics_v1_analytics_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_v1_analytics_proto_depIdxs,
		EnumInfos:         file_proto_analytics_v1_analytics_proto_enumTypes,
		MessageInfos:      file_proto_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_v1_analytics_proto = out.File
	file_proto_analytics_v1_analytics_proto_rawDesc = nil
	file_proto_analytics_v1_analytics_proto_goTypes = nil
	file_proto_analytics_v1_analytics_proto_depIdxs = nil
}
