// Code generated by mockery v2.53.5. DO NOT EDIT.

package profile

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "todoapp/services/user-service/internal/domain/entities"

	ports "todoapp/services/user-service/internal/ports"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

// GetPreferences provides a mock function with given fields: ctx, userID
func (_m *MockUserService) GetPreferences(ctx context.Context, userID int64) (*domain.UserPreferences, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferences")
	}

	var r0 *domain.UserPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.UserPreferences, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.UserPreferences); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfile provides a mock function with given fields: ctx, userID
func (_m *MockUserService) GetProfile(ctx context.Context, userID int64) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GitHubLogin provides a mock function with given fields: ctx, input
func (_m *MockUserService) GitHubLogin(ctx context.Context, input ports.OAuthLoginInput) (*ports.AuthResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GitHubLogin")
	}

	var r0 *ports.AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.OAuthLoginInput) (*ports.AuthResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.OAuthLoginInput) *ports.AuthResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.AuthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.OAuthLoginInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields: ctx, limit, offset
func (_m *MockUserService) ListUsers(ctx context.Context, limit int, offset int) ([]domain.User, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.User, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []domain.User); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, input
func (_m *MockUserService) Login(ctx context.Context, input ports.LoginInput) (*ports.AuthResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *ports.AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.LoginInput) (*ports.AuthResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.LoginInput) *ports.AuthResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.AuthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.LoginInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *MockUserService) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *MockUserService) RefreshToken(ctx context.Context, refreshToken string) (*ports.AuthTokens, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *ports.AuthTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ports.AuthTokens, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ports.AuthTokens); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.AuthTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, input
func (_m *MockUserService) Register(ctx context.Context, input ports.RegisterInput) (*ports.AuthResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *ports.AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.RegisterInput) (*ports.AuthResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.RegisterInput) *ports.AuthResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.AuthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.RegisterInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePreferences provides a mock function with given fields: ctx, userID, input
func (_m *MockUserService) UpdatePreferences(ctx context.Context, userID int64, input ports.UpdatePreferencesInput) (*domain.UserPreferences, error) {
	ret := _m.Called(ctx, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePreferences")
	}

	var r0 *domain.UserPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ports.UpdatePreferencesInput) (*domain.UserPreferences, error)); ok {
		return rf(ctx, userID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ports.UpdatePreferencesInput) *domain.UserPreferences); ok {
		r0 = rf(ctx, userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ports.UpdatePreferencesInput) error); ok {
		r1 = rf(ctx, userID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: ctx, userID, input
func (_m *MockUserService) UpdateProfile(ctx context.Context, userID int64, input ports.UpdateProfileInput) (*domain.User, error) {
	ret := _m.Called(ctx, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ports.UpdateProfileInput) (*domain.User, error)); ok {
		return rf(ctx, userID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ports.UpdateProfileInput) *domain.User); ok {
		r0 = rf(ctx, userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ports.UpdateProfileInput) error); ok {
		r1 = rf(ctx, userID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserRole provides a mock function with given fields: ctx, userID, role
func (_m *MockUserService) UpdateUserRole(ctx context.Context, userID int64, role string) (*domain.User, error) {
	ret := _m.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserRole")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*domain.User, error)); ok {
		return rf(ctx, userID, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *domain.User); ok {
		r0 = rf(ctx, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserStatus provides a mock function with given fields: ctx, userID, isActive
func (_m *MockUserService) UpdateUserStatus(ctx context.Context, userID int64, isActive bool) (*domain.User, error) {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatus")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) (*domain.User, error)); ok {
		return rf(ctx, userID, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) *domain.User); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, bool) error); ok {
		r1 = rf(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
